name: Update Weekly Activity

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests matplotlib pandas

      - name: Generate weekly activity
        run: |
          python .github/scripts/generate_weekly_activity.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "ppankaj.nanotrics@gmail.com"
          git add .
          git commit -m "Update weekly activity graph"
          git push
